### ISSUE TITLE
Implement Slash Commands

### ISSUE THREAD

**Issue by m1stadev** [m1stadev/AutoTSS#11]
TODO:
- [ ] Wait for a text input component to be implemented into Discord's API (more info [here](https://discorddevelopers.notion.site/Discord-Developer-event-9-21-Q-A-follow-ups-102d289cd20b4de8a7540f51ec11bc5f))
    - Necessary for adding devices
- [x] Move to [Pycord](https://github.com/Pycord-Development/pycord)
- [ ] Move all commands to slash commands
    - This will be worked on in #23

**Comment by m1stadev** [comment]
Further looking into slash commands, it doesn't seem like they'll be as useful for AutoTSS as I originally thought, so cancelling this change.

**Comment by ImUrX** [comment]
why not, ephemeral interactions are a great thing
